### PR TITLE
Styling app

### PR DESCRIPTION
**Pull request by SabaAhmad404**
in this  react project, I style my app using

1) CSS
2)setting up the linters

kindly review my project

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @SabaAhmad404   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- Professional PR description :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to align the main containers of your website on the same line vertically in order to match the provided design as much as possible.

   - ### YOUR DESIGN
   
     image

   - ### PROVIDED DESIGN
   
     image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SabaAhmad404** [comment]
hey @levy002 sorry, i don't get you because the containers are perfectly aligned on my computer screen.

**Comment by levy002** [comment]
Hello @SabaAhmad404, Please look at those pictures and let me know if it is clear now.
   
   - ###Your design
    WhatsApp Image 2023-02-04 at 6 05 30 PM

   - ### Provided design
     WhatsApp Image 2023-02-04 at 6 06 48 PM

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @SabaAhmad404, 

To highlight 👍🏽 
✔️ App runs smoothly
✔️ App matches given design
✔️ No linter errors

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by SabaAhmad404** [comment]
hey @levy002  i completed the required changes thanks

**Pull request merged**
